# 全局规划配置文件
GlobalPlanner:

  allow_unknown: true
  visualize_potential: true
  use_dijkstra: true
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false
# 此处需要自己调试
  lethal_cost: 253
  neutral_cost: 66
  cost_factor: 0.55
  default_tolerance: 0.2
 
  publish_scale: 100                            

  planner_costmap_publish_frequency: 0.0        



  publish_potential: true

  orientation_mode: 1     #方向模式

  orientation_window_size: 1